apiVersion: batch/v1
kind: Job
metadata:
  name: archive-job
spec:
  template:
    spec:
      containers:
        - name: finbert-serve
          imagePullPolicy: Always
          image: gcr.io/intrinsic-research/sentiment-pipeline:kuberay
          command: ["python", "business_sentiment.py"]
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_pass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_name
          - name: INSTANCE_CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: instance_connection_name    
      restartPolicy: OnFailure