apiVersion: batch/v1
kind: Job
metadata:
  name: serve-job
spec:
  template:
    spec:
      containers:
        - name: finbert-serve
          imagePullPolicy: Always
          image: gcr.io/intrinsic-research-capital/sentiment-pipeline:kuberay
          command: ["python", "finbert_serve.py"]
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
      restartPolicy: Never
  backoffLimit: 0
