apiVersion: batch/v1
kind: Job
metadata:
  name: archive-job
spec:
  template:
    spec:
      containers:
        - name: finbert-serve
          imagePullPolicy: Always
          image: gcr.io/intrinsic-research-capital/sentiment-pipeline:kuberay
          command: ["python", "archive_sentiment.py"]
          env:
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_user
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_pass
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_name
              - name: INSTANCE_CONNECTION_NAME
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: instance_connection_name
              - name: NYTIMES_API
                valueFrom:
                  secretKeyRef:
                    name: ny-secret
                    key: nytimes_api
      restartPolicy: Never
  backoffLimit: 0
